apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: container-allowed-users
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - demo
      - payments
  parameters:
    runAsUser:
      rule: MustRunAsNonRoot # Buộc container phải chạy với user thường, không dùng root (UID 0)